In [22]:
import numpy as np

a = np.array([1,2,3])
b = 2
print(a+b)

#mean of array and substraction

m = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

column_mean = m.mean(axis=0)     #this gets the mean of n number of columns and gives a 1d array with those means axis=0 represents columns
row_mean = m.mean(axis=1)     #this gets the mean of n number of rows and gives a 1d array with those means axis=1 represents rows

print(column_mean)
print(row_mean)

centered = m - column_mean

print(centered)

#mismached rows/columns

x = np.array([[1],[2],[3]])
y = np.array([10,20,30])

print(x+y)

#DRILLS

d = np.array([[1,2,3,4],
              [5,6,7,8],
                [9,10,11,12]])

col_mean = d.mean(axis=0)

print(d - col_mean)

e = np.arange(1,6)
se = e * 10 + 100

print(se)


t = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])
add = np.array([1,2,3])

print(t + add)


add_column = np.array([[1],
                        [2],
                         [3]])

print(t + add_column)

# ADVENCED DRILLS

ad = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])

r_mean = (ad.mean(axis=1)).reshape(3,1)

print(ad - r_mean)

r_max = ad.max(axis=0)

print(ad / r_max)

ad1 = np.array([[10,11,12],
                [13,14,15],
                 [16,17,18],
                  [19,20,21]])

r1_mean = ad1.mean(axis=0)

ad1_sub = ad1 - r1_mean

r1_sum = (ad1_sub.sum(axis=1)).reshape(4,1)

print(ad1_sub / r1_sum)

ad2 = np.arange(5,30,5)

ad2_mean = ad2.mean()

ad2_std = ad2.std()

ad2_centered = ad2 - ad2_mean

print(ad2_centered)

ad2_scaled = ad2_centered / ad2_std

print(ad2_scaled)






















[3 4 5]
[4. 5. 6.]
[2. 5. 8.]
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]
[110 120 130 140 150]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[0.14285714 0.25       0.33333333]
 [0.57142857 0.625      0.66666667]
 [1.         1.         1.        ]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[-10.  -5.   0.   5.  10.]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
