In [33]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([[3.0,4.0,5.0],[6.0,7.0,8.0]])
print(b)

#Get Dimension
a.ndim
#Get shape
b.shape
#get type
a.dtype

c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

#Get a specific element [row,coloumn]

c[1,5]

#get a specific row

c[1, :]

#get a specific coloumn

c[ : ,2]

#change specific element

c[1,5] = 20

print(c)

#all 0s matrix

np.zeros((2,3))

#all 1s matrix

np.ones((4,2,2))

#all any number matrix

np.full((2,3),7)

#matrix with random decimal numbers

np.random.rand(3,3)

#matrix with random integer numbers

np.random.randint(100,size=(3,3))


#MATH

d = np.array([2,3,4,5])

d * 2

#Linear Algebra

f = np.ones((2,3))
e = np.full((3,2),2)
print(f)
print(e)

np.matmul(f,e)

#STATISTICS

stats = np.array([[1,2,3],[4,5,6]])

np.min(stats)
np.max(stats)
np.sum(stats)

#reorganising arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(8,1)
print(after)






[1 2 3]
[[3. 4. 5.]
 [6. 7. 8.]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
