In [5]:
import numpy as np

u = np.array([[2,0,4],
              [5,1,3],
               [3,2,4]])
print(u.shape)

u_norm = np.linalg.norm(u, axis=1, keepdims=True)
print(u_norm.shape)
print(u_norm)

u_dot = u @ u.T
print(u_dot.shape)
print(u_dot)

u_denominator = u_norm @ u_norm.T
print(u_denominator.shape)
print(u_denominator)

epsilon = 1e-8

u_cosine = np.divide(u_dot, u_denominator, out = np.zeros_like(u_dot,dtype=float), where=u_denominator != 0)
print(u_cosine.shape)
print(u_cosine)






(3, 3)
(3, 1)
[[4.47213595]
 [5.91607978]
 [5.38516481]]
(3, 3)
[[20 22 22]
 [22 35 29]
 [22 29 29]]
(3, 3)
[[20.         26.45751311 24.08318916]
 [26.45751311 35.         31.85906464]
 [24.08318916 31.85906464 29.        ]]
(3, 3)
[[1.         0.83152184 0.91350028]
 [0.83152184 1.         0.91025899]
 [0.91350028 0.91025899 1.        ]]
