In [1]:
"""
NumPy Day 3 – Array Normalization & Filtering
Author: Diar Begolli
Description:
    - Generate a random (6x4) matrix of integers
    - Center and normalize each column
    - Apply a boolean mask to filter rows
"""

import numpy as np

# Step 1: Create a (6x4) matrix with random integers between 10–100
arr1 = np.random.randint(10, 100, size=(6, 4))
print("Original array:\n", arr1)

# Step 2: Compute column means (axis=0 = column-wise)
arr1_mean = arr1.mean(axis=0)
print("\nColumn means:\n", arr1_mean)

# Step 3: Center the array by subtracting column means
arr1_centered = arr1 - arr1_mean
print("\nCentered array (mean subtracted):\n", arr1_centered)

# Step 4: Compute column standard deviations
arr1_std = arr1.std(axis=0)
print("\nColumn std devs:\n", arr1_std)

# Step 5: Normalize each column → (x - mean) / std
# This is z-score normalization
arr1_normalised = (arr1 - arr1_mean) / arr1_std
print("\nNormalized array (z-scores):\n", arr1_normalised)

# Step 6: Apply a boolean mask → select rows where col0 > col1
arr1_mask = arr1[:, 0] > arr1[:, 1]
print("\nMask (True if col0 > col1):\n", arr1_mask)
print("\nFiltered rows (col0 > col1):\n", arr1[arr1_mask])

# Step 7 (optional): Quick validation → check normalization worked
print("\nMeans after normalization (should be ~0):\n", arr1_normalised.mean(axis=0))
print("Stds after normalization (should be ~1):\n", arr1_normalised.std(axis=0))


Original array:
 [[91 67 59 83]
 [48 75 82 69]
 [61 89 11 48]
 [49 20 42 20]
 [78 84 17 35]
 [93 78 13 75]]

Column means:
 [70.         68.83333333 37.33333333 55.        ]

Centered array (mean subtracted):
 [[ 21.          -1.83333333  21.66666667  28.        ]
 [-22.           6.16666667  44.66666667  14.        ]
 [ -9.          20.16666667 -26.33333333  -7.        ]
 [-21.         -48.83333333   4.66666667 -35.        ]
 [  8.          15.16666667 -20.33333333 -20.        ]
 [ 23.           9.16666667 -24.33333333  20.        ]]

Column std devs:
 [18.43908891 22.90135852 26.41127705 22.56102835]

Normalized array (z-scores):
 [[ 1.1388849  -0.08005348  0.82035665  1.24107818]
 [-1.19311752  0.26927078  1.69119678  0.62053909]
 [-0.48809353  0.88058823 -0.99704885 -0.31026955]
 [-1.1388849  -2.13233347  0.1766922  -1.55134773]
 [ 0.43386092  0.66226057 -0.76987316 -0.88648441]
 [ 1.24735013  0.40026738 -0.92132362  0.88648441]]

Mask (True if col0 > col1):
 [ True False False  Tr