In [2]:
import numpy as np

a = np.array([1,2,3], dtype = float)

b = np.array([4,5,6], dtype = float)

print("Element wise multiplication: ", a*b) #Multiplies each same-position element of two arrays and gives and array of same length
print("Dot multiplication: ", a @ b)        #Multiplies each same-position element of two arras and sums them up gives a single value

m = np.array([[1,2,3],
              [4,5,6]], dtype=float)    #(2,3) - 2 by 3 array [2 rows 3 columns]

n = np.array([[0.1],
              [0.2],
               [0.3]])                  #(3,1) - 3 by 1 array [3 rows 2 colums]

print("m shape: ", m.shape, "n shape: ", n.shape)
print("m @ n: ", m @ n)
print("m.T: ", m.T)

v = np.array([3,4], dtype=float)

print("||v|| : ", np.linalg.norm(v))    #L2 norm - length of the vector from the origin pythagorian


r = np.array([
    [5, 4, 0, 3, 0, 1],
    [4, 0, 0, 5, 2, 2],
    [0, 2, 4, 0, 4, 5],
    [5, 5, 1, 0, 0, 0],
    [0, 3, 5, 0, 4, 4]
], dtype=float)

print("r shape: ", r.shape)   #(m users,n items) prints the 5 by 6 matrix(5 users 6 items)

row_norms = np.linalg.norm(r, axis=1, keepdims=True) # row norms L2(length of each users vector) - keepdims true keeps shape [m,1] not [m,:]

print("first 3 row norms: ", row_norms[:3])

dot_matrix = r @ r.T          # all pairwise dot production (numerator for cosine) - (m,1) @ (1,m) -> (m,m)

denom = row_norms @ row_norms.T   #All pairwise norm products (denominator) - (m,1) @ (1,m) -> (m,m)

print("denom shape:", denom.shape)

eps = 1e-8

cos_sim = dot_matrix / (denom + eps)  #Safe cosine similarity: elementwise division - Add epsilon to denom


for i in range(cos_sim.shape[0]):
    cos_sim[i, i] = 1.0 if row_norms[i,0] > 0 else 0.0    # Optional normalize diagonal to exactly 1 (if row not all zeros)

print("\nCosine similarity (rounded):\n", np.round(cos_sim, 3))


#find top-3 similar users for user 0 (excluding self)

user_id = 0
scores = cos_sim[user_id]                 # shape (m,)
order = np.argsort(-scores)               # descending
top_neighbors = [u for u in order if u != user_id][:3]
print(f"\nTop similar to user {user_id}:", top_neighbors,
      "scores:", np.round(scores[top_neighbors], 3))


Element wise multiplication:  [ 4. 10. 18.]
Dot multiplication:  32.0
m shape:  (2, 3) n shape:  (3, 1)
m @ n:  [[1.4]
 [3.2]]
m.T:  [[1. 4.]
 [2. 5.]
 [3. 6.]]
||v|| :  5.0
r shape:  (5, 6)
first 3 row norms:  [[7.14142843]
 [7.        ]
 [7.81024968]]
denom shape: (5, 5)

Cosine similarity (rounded):
 [[1.    0.74  0.233 0.882 0.276]
 [0.74  1.    0.329 0.4   0.281]
 [0.233 0.329 1.    0.251 0.977]
 [0.882 0.4   0.251 1.    0.345]
 [0.276 0.281 0.977 0.345 1.   ]]

Top similar to user 0: [np.int64(3), np.int64(1), np.int64(4)] scores: [0.882 0.74  0.276]
