In [18]:
import numpy as np

np.random.seed(42)

SUBJECTS = ["Math","Science","English"]         #Create the subject list manually

scores = np.random.randint(50,101,size=(20,3))  #Create a random matrix consisting of 20 students(rows) 3 subjects(columns) grades range 50-100

print("score shape: ", scores.shape)            #print scores matrix shape

print(scores[:5])                               #print first 5 students grades

subject_mean = scores.mean(axis=0)

subject_variance = scores.var(axis=0)

subject_stdev = scores.std(axis=0)

print("Per subject means: ", dict(zip(SUBJECTS, np.round(subject_mean, 2))))

print("Per subject variance: ", dict(zip(SUBJECTS,np.round(subject_variance,2))))

print("Per subject standard deviation: ", dict(zip(SUBJECTS,np.round(subject_stdev,2))))

scores_cov = np.cov(scores, rowvar=False)

print("Covariance matrix:\n", np.round(scores_cov, 2))

scores_corr = np.corrcoef(scores,rowvar=False)

print("Correlation matrix:\n", np.round(scores_corr, 2))


corr_c = scores_corr.copy()

np.fill_diagonal(corr_c, -1)

best_match = np.unravel_index(np.argmax(corr_c),corr_c.shape)

i, j = best_match

print("Strongest pair:", SUBJECTS[i], "&", SUBJECTS[j],
      "with correlation =", scores_corr[i, j])

z = (scores - subject_mean)/ subject_stdev

z_corr = np.corrcoef(z, rowvar=False)

print("z: ", z)
print("z corr", z_corr)



score shape:  (20, 3)
[[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]]
Per subject means:  {'Math': np.float64(78.6), 'Science': np.float64(73.2), 'English': np.float64(72.15)}
Per subject variance:  {'Math': np.float64(157.54), 'Science': np.float64(293.36), 'English': np.float64(189.73)}
Per subject standard deviation:  {'Math': np.float64(12.55), 'Science': np.float64(17.13), 'English': np.float64(13.77)}
Covariance matrix:
 [[ 165.83   17.4    16.48]
 [  17.4   308.8  -106.82]
 [  16.48 -106.82  199.71]]
Correlation matrix:
 [[ 1.    0.08  0.09]
 [ 0.08  1.   -0.43]
 [ 0.09 -0.43  1.  ]]
Strongest pair: Math & English with correlation = 0.09057976614033476
z:  [[ 0.74891483  0.28024688 -0.5916876 ]
 [ 1.067602   -0.94583323 -0.15608937]
 [ 0.74891483 -0.30360079 -0.01088996]
 [-1.48189531 -0.77067892  0.06170975]
 [ 0.50989946  0.92247932  0.06170975]
 [-2.11926964 -0.12844649 -1.53548377]
 [-0.44616203  1.15601839  0.49730798]
 [ 0.66924304 -1.29614183 -0.15608937]
 [ 