In [28]:
import numpy as np

a = np.array([1,2,3,4])     # 1D array - vector
b = np.array([[1,2,3],[4,5,6]])   #2D array - matrix

print("a:" , a)
print("b:" , b)

print("a shape: ", a.shape)
print("b shape: ", b.shape)

print("a dimensions", a.ndim)
print("b dimensions", b.ndim)

zeros = np.zeros((2,3))
print("zeros: ", zeros)

ones = np.ones((3,2))
print("ones: ", ones)

arange = np.arange(0,10,1)
print("arange: ", arange)

linspace = np.linspace(0,1,5)
print("linspace: ", linspace)

arr = np.array([10,20,30,40,50])

print("First element: ", arr[0])
print("Last element: ", arr[-1])
print("Slice 1st to 3rd element: ", arr[1:4])
print("Every second element: ", arr[::2])


matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Element at row 0 column 1: ", matrix[0,1])
print("Frist row: ", matrix[0,:])
print("First column: ", matrix[:,0])

x = np.array([1,2,3,4,5])

print("Sum: ", x.sum())
print("Mean: ", x.mean())
print("Std dev: ", x.std())
print("Min: ", x.min())
print("Max: ", x.max())

y = np.array([5,10,15,20,25])

mask = y > 12

print("Mask: ", mask)
print("Filtered: ", y[mask])

#EXERCISE

ex = np.arange(1,20,1)

print(ex)

select = ex % 2 == 1

print(ex[select])

print(ex[select].mean())


f = np.arange(1, 7)   # → [1 2 3 4 5 6]
print("Original:", f, "Shape:", f.shape)

d = f.reshape(2, 3)   # 2 rows, 3 columns
print("Reshaped:\n", d, "Shape:", d.shape)

#DRILLS

w = np.arange(1,30)

sel = w % 2 == 0

print(w[sel])

print(w[sel].mean())

sel_2 = (w % 3 == 0) & (w > 10)

print(w[sel_2])

print(w[sel_2].sum())

sh = np.arange(0,12)

rsh = sh.reshape(3,4)

print(rsh[1:2])
print(rsh[:,-1])















a: [1 2 3 4]
b: [[1 2 3]
 [4 5 6]]
a shape:  (4,)
b shape:  (2, 3)
a dimensions 1
b dimensions 2
zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
arange:  [0 1 2 3 4 5 6 7 8 9]
linspace:  [0.   0.25 0.5  0.75 1.  ]
First element:  10
Last element:  50
Slice 1st to 3rd element:  [20 30 40]
Every second element:  [10 30 50]
Element at row 0 column 1:  2
Frist row:  [1 2 3]
First column:  [1 4 7]
Sum:  15
Mean:  3.0
Std dev:  1.4142135623730951
Min:  1
Max:  5
Mask:  [False False  True  True  True]
Filtered:  [15 20 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
10.0
Original: [1 2 3 4 5 6] Shape: (6,)
Reshaped:
 [[1 2 3]
 [4 5 6]] Shape: (2, 3)
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
15.0
[12 15 18 21 24 27]
117
[[4 5 6 7]]
[ 3  7 11]
